//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UesrId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Birthday { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsEmailConfirm { get; set; }
        public Nullable<System.Guid> ActionCode { get; set; }
        public string UserAccount { get; set; }
        public string ResetPwdCode { get; set; }
    }
}
